import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../wechat-share.js',import.meta.url),'utf8').replace('export async function','async function');
function integration(endpoint='/api/wechat-signature',ua='MicroMessenger'){const calls=[],context=vm.createContext({URL,encodeURIComponent,console:{warn(){}},document:{querySelector:()=>({content:endpoint})},navigator:{userAgent:ua},location:{href:'https://game.example/entry?from=report#last',origin:'https://game.example'},fetch:async url=>{calls.push(['fetch',url]);return {ok:true,json:async()=>({appId:'demo',timestamp:1,nonceStr:'n',signature:'s'})};},window:{wx:{config:c=>calls.push(['config',c]),ready:cb=>cb(),error(){},updateAppMessageShareData:c=>calls.push(['friends',c]),updateTimelineShareData:c=>calls.push(['timeline',c])}}});vm.runInContext(source,context);return {calls,context};}
test('actual app configuration supplies all WeChat fields to both sharing APIs',async()=>{const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'),call=app.match(/setupWeChatShare\((\{title:[\s\S]*?\})\);/)[1],{calls,context}=integration();vm.runInContext("function shareURL(){return 'https://game.example/?from=report';}",context);await vm.runInContext('setupWeChatShare('+call+')',context);for(const kind of ['friends','timeline']){const c=calls.find(a=>a[0]===kind)[1];assert.equal(c.title,'你真的懂异性吗？');assert.equal(c.link,'https://game.example/?from=report');assert.equal(c.imgUrl,'https://game.example/assets/manga-cover-v7.webp');if(kind==='friends')assert.ok(c.desc.includes('异性'));}const request=new URL(calls.find(c=>c[0]==='fetch')[1]);assert.equal(request.searchParams.get('url'),'https://game.example/entry?from=report');});
test('disabled configuration and non-WeChat browsers send no requests',async()=>{for(const [endpoint,ua] of [['','MicroMessenger'],['/api/sign','Edge']]){const {calls,context}=integration(endpoint,ua);assert.equal(await vm.runInContext('setupWeChatShare({})',context),false);assert.equal(calls.length,0);}});
test('signature endpoint must be same-origin',async()=>{const {calls,context}=integration('https://other.example/sign');assert.equal(await vm.runInContext('setupWeChatShare({})',context),false);assert.equal(calls.length,0);});
