import {STORAGE_KEY,loadRun,makeReport} from './game-core.js';
import {buildRounds} from './game-data.js';
import {validateReportCopy} from './report-ai.js';
export function reportFacts(run){const r=makeReport(run),rounds=buildRounds(run.gender,run.edition);return {typeId:r.type.id,typeName:r.name,classifierVersion:r.assessment.version,score:r.score,skills:r.assessment.skills.map(({id,label,hits,total,value})=>({id,label,hits,total,value})),bias:r.assessment.bias.map(({id,count,total,value})=>({id,count,total,value})),evidence:r.evidence.map(a=>{const q=rounds[a.id-1];return {id:a.id,context:q.context,pick:a.assessmentVersion===1?q.choices[a.pick]:q.originalChoices[a.pick],basis:a.assessmentVersion===1?q.bases?.[a.pick]?.text||null:null,authoredThought:q.thought,matched:a.pick===q.correct};})};}
export function narrativeRequest(run,model){const facts=reportFacts(run);return {model,store:false,input:[{role:'system',content:'你为中国都市恋爱杂志写报告的两段短评。固定人格、分数、真实答题证据都是输入事实，你不得分类、改分、创造题目或经历。opening用温和有趣的比喻提示如何看待本局；closing只邀请下一次对话。每段四十至一百个汉字，不写任何数字或新增事实，不诊断人格，不给男女群体下结论，不羞辱，不输出标签或HTML。只润色措辞，具体证据已由页面固定呈现。'},{role:'user',content:JSON.stringify(facts)}],text:{format:{type:'json_schema',name:'relationship_report_copy',strict:true,schema:{type:'object',additionalProperties:false,required:['typeId','classifierVersion','opening','closing'],properties:{typeId:{type:'string',enum:[facts.typeId]},classifierVersion:{type:'string',enum:[facts.classifierVersion]},opening:{type:'string'},closing:{type:'string'}}}}},max_output_tokens:600};}
export function createReportHandler({apiKey=process.env.OPENAI_API_KEY,model=process.env.OPENAI_REPORT_MODEL,fetcher=fetch}={}){return async(req,res)=>{
 const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
 if(req.method!=='POST'){send(405,{error:'POST required'});return;}if(!apiKey||!model){send(503,{error:'Report copy is not configured'});return;}
 const origin=req.headers.origin;if(origin){try{if(new URL(origin).host!==req.headers.host){send(403,{error:'Same origin required'});return;}}catch{send(403,{error:'Same origin required'});return;}}
 try{let body='';for await(const chunk of req){body+=chunk;if(body.length>20000){send(413,{error:'Too large'});return;}}const parsed=JSON.parse(body),run=loadRun({getItem:key=>key===STORAGE_KEY?JSON.stringify(parsed.run):null});if(!run?.finished){send(400,{error:'Complete answers required'});return;}
 const response=await fetcher('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify(narrativeRequest(run,model)),signal:AbortSignal.timeout(3000)});if(!response.ok){send(502,{error:'Copy unavailable'});return;}const result=await response.json(),text=result.output?.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join(''),copy=JSON.parse(text);if(!validateReportCopy(copy,makeReport(run))){send(502,{error:'Copy failed validation'});return;}send(200,copy);
 }catch{send(502,{error:'Copy unavailable'});}
};}
