import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {newRun,commitAnswer,loadRun,STORAGE_KEY,makeReport} from '../game-core.js';
import {buildRounds} from '../game-data.js';
import {PERSONALITIES} from '../personality.js';
import {createActiveTimer} from '../active-timer.js';
import {enhanceReport} from '../report-ai.js';
import {createReportHandler,narrativeRequest} from '../report-service.js';
function completed(picker=q=>q.correct??0,spentMs=14000){const r=newRun('male','test');for(const q of buildRounds('male'))commitAnswer(r,picker(q),q.id-1,spentMs);return r;}
test('six abilities have item evidence; three cores aggregate them; behavior has authored next actions',()=>{for(const g of ['male','female']){const r=newRun(g,'test');for(const q of buildRounds(g)){if(q.assessment.skills.includes('behavior'))assert.ok(q.behaviorOutcome);commitAnswer(r,q.correct??0,q.id-1,14000);}const a=makeReport(r).assessment;assert.equal(a.skills.length,6);for(const s of a.skills){assert.ok(s.total>=4);assert.equal(s.hits,s.total);assert.equal(s.value,100);}assert.deepEqual(a.axes.map(a=>a.value),[100,100,100]);assert.equal(a.bias.length,2);}for(const group of ['情绪读取','动机理解','关系判断'])assert.equal(PERSONALITIES.filter(t=>t.group===group).length,4);});
test('explicit attribution counters are independent of correctness and have their own denominators',()=>{const best=makeReport(completed()),wrong=makeReport(completed(q=>{const picks=[0,1,2,3].filter(p=>p!==q.correct);return q.bases?picks.find(p=>q.bases[p].kind==='context'):picks[0];}));assert.equal(best.score,100);assert.equal(best.assessment.bias[0].count,2);assert.equal(best.assessment.bias[0].total,8);assert.equal(wrong.score,0);assert.deepEqual(wrong.assessment.bias.map(b=>b.value),[0,0]);assert.equal(best.type.id,'observer');});
test('old answers have no invented attribution, behavior or time evidence; migrate without deleting originals',()=>{const original={...completed(),version:4,answers:completed().answers.map(({id,pick})=>({id,pick}))},storage={getItem:key=>key==='heart-decoder-solo-v4'?JSON.stringify(original):null};const run=loadRun(storage);assert.equal(run.version,7);assert.equal(run.answers.length,30);const r=makeReport(run);assert.deepEqual(r.assessment.bias.map(b=>b.value),[null,null]);assert.equal(r.assessment.skills.find(s=>s.id==='behavior').value,null);assert.equal(r.assessment.tempo.eligible,false);assert.notEqual(r.type.id,'intuitive');assert.equal(original.version,4);});
test('fast type requires enough valid visible times and a matching-score floor',()=>{const quick=makeReport(completed(q=>q.id<=6?(q.correct+1)%4:q.correct??0,4000));assert.equal(quick.type.id,'intuitive');assert.equal(quick.assessment.tempo.count,29);const empty=makeReport(completed(undefined,null)),rushed=makeReport(completed(q=>q.correct===null?0:(q.correct+1)%4,4000)),spam=makeReport(completed(undefined,100));assert.equal(empty.assessment.tempo.eligible,false);assert.notEqual(rushed.type.id,'intuitive');assert.equal(spam.assessment.tempo.eligible,false);});
test('active timer excludes hidden and disabled intervals and can resume saved elapsed time',()=>{let now=0;const timer=createActiveTimer(()=>now);now=310;timer.begin(0);now=2310;assert.deepEqual(timer.snapshot(),{index:0,ms:2000});timer.pause();now=90000;assert.equal(timer.snapshot().ms,2000);timer.resume();now=91000;assert.equal(timer.pause(),3000);const restored=createActiveTimer(()=>now);restored.begin(0,3000);now+=500;assert.equal(restored.snapshot().ms,3500);restored.reset();now+=310;assert.deepEqual(restored.snapshot(),{index:null,ms:0});});
test('missing AI, timeout, wrong type and malformed copy all retain full local report',async()=>{const run=completed(),r=makeReport(run),base='https://game.example/',fetcher=async()=>{throw Error('offline');};assert.equal((await enhanceReport(r,run,{endpoint:'',base,fetcher})).source,'local');for(const f of [fetcher,async()=>({ok:true,json:async()=>({typeId:'invented',opening:'错误分类',closing:'错误分类'})}),async()=>({ok:false})])assert.equal((await enhanceReport(r,run,{endpoint:'/api/report',base,fetcher:f})).source,'local');let sent=false;await enhanceReport(r,run,{endpoint:'https://other.example/api',base,fetcher:()=>{sent=true;}});assert.equal(sent,false);});
test('AI service recomputes canonical type and facts, sends strict copy schema, keeps API key on server',async()=>{const run=completed(),report=makeReport(run),request=narrativeRequest(run,'configured-model');assert.equal(request.store,false);assert.equal(request.text.format.strict,true);assert.deepEqual(request.text.format.schema.properties.typeId.enum,[report.type.id]);let posted;const handler=createReportHandler({apiKey:'test-secret',model:'configured-model',fetcher:async(url,options)=>{posted=JSON.parse(options.body);const copy={typeId:report.type.id,classifierVersion:report.assessment.version,opening:'这一局像一张关系地图，带着好奇再往前走一点。',closing:'下次遇到沉默，可以先给对话留一扇门。'};return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify(copy)}]}]})};}}),server=http.createServer(handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const url=`http://127.0.0.1:${server.address().port}`,res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({run,typeId:'invented',score:999})}),copy=await res.json();assert.equal(res.status,200);assert.equal(copy.typeId,report.type.id);assert.equal(JSON.stringify(copy).includes('test-secret'),false);assert.equal(JSON.parse(posted.input[1].content).score,100);}finally{await new Promise(resolve=>server.close(resolve));}});
