import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/Mayn/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'}),base='http://localhost:4174',out={doubleTap:[],weakNetwork:{},audio:{},security:{},layout:[]};
const ready=async page=>{await page.waitForFunction(()=>!document.querySelector('#app[aria-busy="true"]')&&document.querySelector('[data-action]'));await page.waitForTimeout(100);};
async function start(width=390){const context=await browser.newContext({viewport:{width,height:740},isMobile:true,hasTouch:true}),page=await context.newPage();await page.goto(base);await ready(page);await page.locator('[data-gender="male"]').click();await ready(page);return {context,page};}
try{
for(const delay of [40,100,160,200,250,350])for(const nth of [0,1,2,3]){const {context,page}=await start();await page.locator('.choice').nth(nth).dblclick({delay});await ready(page);out.doubleTap.push({delay,nth,round:await page.locator('.round-number b').textContent()});await context.close();}
for(const width of [320,375,390,430]){const {context,page}=await start(width);out.layout.push(await page.evaluate(width=>({width,overflow:document.documentElement.scrollWidth>innerWidth,choices:[...document.querySelectorAll('.choice')].map(n=>n.getBoundingClientRect().height),back:document.querySelector('.back-button').getBoundingClientRect().height,body:parseFloat(getComputedStyle(document.querySelector('.scene-context')).fontSize)}),width));await context.close();}
{
 const {context,page}=await start();let release;const blocked=new Promise(r=>release=r);await page.route('**/api/action',async route=>{await blocked;await route.abort('failed');});
 await page.locator('.choice').first().click();await page.waitForTimeout(500);out.weakNetwork.waiting={busy:await page.locator('#app').getAttribute('aria-busy'),disabled:await page.locator('.choice:disabled').count(),text:await page.locator('#app').innerText()};release();await page.waitForTimeout(300);out.weakNetwork.failure={round:await page.locator('.round-number b').textContent(),picked:await page.locator('.picked').count(),disabled:await page.locator('.choice:disabled').count(),toast:await page.locator('#toast').innerText()};await page.unroute('**/api/action');await page.locator('.choice').first().click();await ready(page);out.weakNetwork.retryRound=await page.locator('.round-number b').textContent();await context.close();
}
{
 const {context,page}=await start();await page.evaluate(()=>{window.originalPlay=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){return Promise.reject(new DOMException('blocked','NotAllowedError'));};});await page.locator('#sound').click();await page.waitForTimeout(100);out.audio.blocked={pressed:await page.locator('#sound').getAttribute('aria-pressed'),label:await page.locator('#sound').innerText(),round:await page.locator('.round-number b').innerText()};await page.evaluate(()=>HTMLMediaElement.prototype.play=window.originalPlay);await page.locator('#sound').click();await page.waitForTimeout(500);out.audio.retry={paused:await page.locator('#bgm').evaluate(a=>a.paused),duration:await page.locator('#bgm').evaluate(a=>a.duration)};await context.close();
}
{
 const {context,page}=await start();out.security=await page.evaluate(async()=>{const s=await(await fetch('/api/game')).json();const first=document.querySelector('.choice');const payload={action:'answer',questionId:first.dataset.questionId,pick:Number(first.dataset.pick),revision:s.revision,requestId:'concurrency-review-123'};const rs=await Promise.all([fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,requestId:'concurrency-review-456'})})]);const bodies=await Promise.all(rs.map(r=>r.json()));const latest=await(await fetch('/api/game')).json();return {concurrentStatuses:rs.map(r=>r.status),round:/round-number"><b>(\d+)/.exec(latest.html)?.[1],leaks:/optionDistances|benchmark|OPENAI|rr_v2/.test(JSON.stringify(latest)),bodies:bodies.map(b=>({screen:b.screen,error:b.error}))};});out.security.cookie=await context.cookies();await context.close();
}
}finally{fs.writeFileSync('artifacts/v2-review/mobile-probe.json',JSON.stringify(out,null,2));await browser.close();}
